app/urls.py
from django.conf.urls import url

from app import views

app_name = 'app'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^test/$', views.test, name='test'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^search/$', views.search, name='search')

]

demon/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^app/', include('app.urls')),
    url(r'^admin/', admin.site.urls),
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import HttpResponse, render
import json
import requests

def index(request):
    return HttpResponse('hello world')

def test(request):
    return HttpResponse('This is test')

def search(request):
    return render(request, 'app/search.html')

def profile(request):
    # req = requests.get('https://api.github.com/users/paige0701')
    # content = req.text
    # return render(request, 'app/profile.html')
    jsonList = []
    if request.method =='POST':
        user = request.POST.get('user')
        req = requests.get('https://api.github.com/users/' + user)
        jsonList.append(json.loads(req.text))
        parsedData = []
        userData = {}
        for data in jsonList:
            userData['name'] = data['name']
            userData['blog'] = data['blog']
            userData['email'] = data['email']
            userData['public_gists'] = data['public_gists']
            userData['public_repos'] = data['public_repos']
            userData['avatar_url'] = data['avatar_url']
            userData['followers'] = data['followers']
            userData['following'] = data['following']
            parsedData.append(userData)

            context = {'userData': userData}
            return render(request,'app/profile.html', context)

app/templates/app/profile.html
<!DOCTYPE html>
<html>
<head>
    <script src="/static/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="/static/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap-theme.min.css">
</head>
<body>
<h1 class="text-center"> Github User Data </h1>


<div class="col-lg-12">


    <h3>Searched data</h3>
    <div class="table-responsive">
        <table class="table table-bordered table-hover table-striped tablesorter">
            <thead>
            <tr>
                <th class="header"> Username <i class="icon-sort"></i></th>
                <th class="header"> Blog <i class="icon-sort"></i></th>
                <th class="header"> Public Repos <i class="icon-sort"></i></th>
                <th class="header"> Public Gists <i class="icon-sort"></i></th>
                <th class="header"> Email <i class="icon-sort"></i></th>
                <th class="header"> Followers <i class="icon-sort"></i></th>
                <th class="header"> Following <i class="icon-sort"></i></th>
            </tr>
            </thead>
            <tbody>

            {#            {% for key in userData %}#}
            <tr>
                <td>{{ userData.name}}</td>
                <td>{{ userData.blog }}</td>
                <td>{{ userData.public_repos }}</td>
                <td>{{ userData.public_gists }}</td>
                <td>{{ userData.email }}</td>
                <td>{{ userData.followers }}</td>
                <td>{{ userData.following }}</td>
            </tr>
            {#            {% endfor %}#}

            </tbody>
        </table>
    </div>
</div>


</body>
</html>

app/templates/app/search.html
<!DOCTYPE html>
<html>
<head>
    <script src="/static/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="/static/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap-theme.min.css">
</head>
<body>
<div class="container text-center">
    <form class="form-signin" id="login_form" method="post" action="{% url 'app:profile'%}">
        {% csrf_token %}

        <br>
        <input type="text" name="user" class="form-control" placeholder="Github User Name, e.g: DrkSephy" value="" required autofocus>
        <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Get Data</button>
    </form>
</div>
</body>
</html>